version: "3.8"

services:
  mariadb:
    image: mariadb:10.6
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: prestashop
      MARIADB_USER: ps_user
      MARIADB_PASSWORD: ps_pass
      MARIADB_ROOT_PASSWORD: mypassword   # <- mantengo la clave que usas ahora
    volumes:
      - db_data:/var/lib/mysql:rw
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p\"$${MARIADB_ROOT_PASSWORD}\" --silent"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  phpmyadmin:
    image: phpmyadmin:5
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_started
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: mypassword
    ports:
      - "127.0.0.1:8081:80"

  prestashop:
    image: prestashop/prestashop:8.1
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_started
    environment:
      DB_SERVER: mariadb
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: mypassword
      PS_INSTALL_AUTO: 0
      PS_ENABLE_SSL: "1"
      PS_LANGUAGE: es
      PS_COUNTRY: CL
      PS_DOMAIN: www.entrecopasyvinos.cl
      PS_HANDLE_DYNAMIC_DOMAIN: 1
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ps_data:/var/www/html:rw

volumes:
  db_data:
  ps_data:
